name: pr-bot
on:
  pull_request:
    types:
      - opened
      - converted_to_draft
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  push:

jobs:
  run-pr-bot:
    permissions:
      contents: read
      pull-requests: write
    # TODO modify repo
    if: ${{ github.event.issue.pull_request && github.repository == 'raulcd/arrow' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v3
        with:
          path: arrow
          # fetch the tags for version number generation
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Archery and Crossbow dependencies
        run: pip install -e arrow/dev/archery[bot]
      - name: Handle PR workflow event
        env:
          ARROW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
        run: |
          archery trigger-bot \
            --event-name ${{ github.event_name }} \
            --event-payload ${{ github.event_path }}